# Change these first
owner: iesitalia # Your GitHub organization or username, where this repository lives
repo: status-check # The name of this repository

sites:
  - name: IES Italia
    url: https://ies-italia.it
  - name: Seafy
    url: https://seafy.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ies-italia.it
  #baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status HiWay Media
  introTitle: "**HiWay Media** Status Dashboard."
  introMessage: " "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "IES Italia"
  commitAuthorEmail: "github-bot@ies-italia.it"

i18n:
  footer: "If you are experiencing an issue not listed here, please [contact support](mailto:support@ies-italia.it)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
